[package]
name = "draught-of-fpl"
version = "0.1.0"
authors = ["fl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2" # Web server-framework
reqwest = "0.9.22" # Web client
serde = "1.0.102" # Serialize/deserialize 
serde_json = "1.0.41" #Json deserialization/serialization
